name: Collect and commit latest version

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of publication'
        required: true
        default: release
      branch:
        description: 'Branch to collect from'
        required: true
        default: 'main'
      tag:
        description: 'Release tag'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Check if the tag is >= v1.14.0 and create environment variables
      - name: Check tag version
        id: check_version
        run: |
          version=${{ inputs.tag }}
          if [ "$(printf '%s\n' "v1.14.0" "$version" | sort -V | head -n1)" != "v1.14.0" ]; then
            echo "Tag is less than v1.14.0. Exiting."
            exit 1
          fi
          dest="releases/${{ inputs.tag }}"
          echo "dest=$dest" >> $GITHUB_ENV
          major=$(echo "$version" | cut -d'.' -f1 | sed 's/v//' | awk '{print $1 + 0}')
          echo "major=$major" >> $GITHUB_ENV
          branch="collect/${{ inputs.tag }}"
          echo "branch=$branch" >> $GITHUB_ENV

      # Checkout the dsfr repository
      - name: Checkout dsfr
        uses: actions/checkout@v4
        with:
          repository: GouvernementFR/dsfr
          ref: ${{ inputs.branch }}
          path: dsfr

      # Checkout the dsfr-archive
      - name: Checkout dsfr-archive
        uses: actions/checkout@v4
        with:
          repository: GouvernementFR/dsfr-archive
          token: ${{ secrets.GITHUB_TOKEN }}
          path: archive

      # Set up Node.js and Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
        continue-on-error: false

      # Install dependencies
      - name: Install dependencies
        run: |
          if [ "${{ env.major }}" -gt 1 ]; then
            corepack enable
          fi          
          yarn install
        working-directory: dsfr
        continue-on-error: false

      # Build the project
      - name: Build the project
        run: yarn archive
        working-directory: dsfr

      # Create branch and remove existing release folder if it exists
      - name: Remove existing release folder
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # Check if the branch already exists
          if git show-ref --verify --quiet refs/heads/${{ env.branch }}; then
            echo "Branch ${{ env.branch }} already exists. Deleting it."
            git branch -D ${{ env.branch }}
            if git ls-remote --exit-code --heads origin "${{ env.branch }}"; then
              git push origin --delete "${{ env.branch }}"
            fi
          fi
          # Create a new branch
          git checkout -b ${{ env.branch }}
          if [ -d "${{ env.dest }}" ]; then
            git rm -r --ignore-unmatch ${{ env.dest }}
            git commit -m "remove existing release folder"
          fi
        working-directory: archive

      # Copy archive files to the destination folder
      - name: Copy files to folder
        run: |
          mkdir -p archive/${{ env.dest }}
          cp -r dsfr/.archive/* archive/${{ env.dest }}

      # Commit and push changes to the branch
      - name: Commit and push release
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "add release files for ${{ inputs.tag }}"
          # merge the branch into the main branch squash
          git checkout main
          git merge --squash ${{ env.branch }}
          if [ "${{ inputs.type }}" != "release" ]; then
            if git show-ref --verify --quiet refs/heads/"${{ inputs.type }}"; then
              git branch -D "${{ inputs.type }}"
            fi
            if git ls-remote --exit-code --heads origin "${{ inputs.type }}"; then
              git push origin --delete "${{ inputs.type }}"
            fi
            git checkout -b "${{ inputs.type }}"
          fi
          git commit -m "🚚 chore: collected DSFR release ${{ inputs.tag }}"
          git push
        working-directory: archive

      # Trigger the release workflow
      - name: Trigger release workflow
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'release-trigger',
                client_payload: {
                    type: '${{ inputs.type }}',
                    branch: '${{ inputs.branch }}',
                    tag: '${{ inputs.tag }}'
                }
            });
