name: Build, release and Increment version

on:
  push:
    branches:
      - main

  repository_dispatch:
    types: [ release-trigger ]

  workflow_dispatch:
    inputs:
      type:
        description: 'Type of publication'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - test

jobs:
  increment-build-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set environment variables based on the type of publication
      - name: Set up environment variables
        run: |
          if [ -n "${{ github.event.inputs.type }}" ]; then
            TYPE="${{ github.event.inputs.type }}"
          elif [ -n "${{ github.event.client_payload.type }}" ]; then
            TYPE="${{ github.event.client_payload.type }}"
          else
            TYPE="release"
          fi
          echo "TYPE=$TYPE" >> $GITHUB_ENV
          if [ "${TYPE}" != 'release' ]; then
            echo "BRANCH=${TYPE}" >> $GITHUB_ENV
            git checkout -b "${BRANCH}"
          else
            echo "BRANCH=main" >> $GITHUB_ENV
          fi
          if [ ! -d "releases" ]; then
              echo "Releases directory does not exist or is empty."
              exit 1
          fi
          LATEST_TAG=$(git describe --tags --abbrev=0)
          VERSION=${LATEST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "${VERSION}"
          PATCH=$((PATCH + 1))
          TAG="v$MAJOR.$MINOR.$PATCH"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "RELEASE=${TAG}-${TYPE}" >> $GITHUB_ENV
          echo "FILE=archive-${RELEASE}.zip" >> $GITHUB_ENV

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      # Enable corepack
      - name: Enable corepack
        run: |
          corepack enable
          yarn

      # Build the project
      - name: Build the project
        run: |
          yarn dsfr configure
          yarn dsfr interpret
          yarn dsfr publish

      # Perform the release using the current version
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          mv .doc www
          mv .env env
          zip -r ${{ env.FILE }} www env -x "*.DS_Store"
          gh release create ${{ env.TAG }} ${{ env.FILE }} --title "Release ${{ env.TAG }}" --notes "Automated release for version ${{ env.TAG }}"
